#!/bin/sh

PTTRN=".*TODO: \[#[0-9]*\].*"
flg=true

fl=(`find . -type d -name .git -prune -o -type f -print`)
for f in ${fl[@]}
do
    if grep -E "$PTTRN" $f -q; then
        if "${flg}" ; then
            ESC=$(printf '\033')
            printf "${ESC}[33m%s${ESC}[m\n" 'WARNING: REMAINING TODO COMMENT'
            flg=false
        fi
        
        echo \[$f\]
        grep -E "$PTTRN" $f -n
        echo
    fi
done