version: '3.8'
services:
  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: postgres-syani
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5423:5432
    user: root
    volumes:
      - pg-data-idol:/var/lib/pgdata
volumes:
  pg-data-idol:
    driver: local