version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: faaaar-server
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./server:/go/src
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: faaaar-db
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    user: root
    volumes:
      - pg-data-idol:/var/lib/pgdata
volumes:
  pg-data-idol:
    driver: local