version: '3.8'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: faaaar-front
    tty: true
    ports:
      - 8081:8081
    volumes:
      - ./front:/go/src
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: faaaar-server
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./server:/go/src
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: faaaar-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 5432:5432
    user: root
    volumes:
      - pg-data-idol:/var/lib/pgdata
      - ./db:/db
volumes:
  pg-data-idol:
    driver: local