version: '3'

tasks:
  build:
    cmds:
      - docker-compose up --build -d
  up:
    cmds:
      - docker-compose up -d
  rbuild:
    cmds:
      - task stop
      - task build
  stop:
    cmds:
      - docker stop faaaar-front
      - docker stop faaaar-server
      - docker stop faaaar-db
  es:
    cmds:
      - docker exec -it faaaar-server sh
  ed:
    cmds:
      - docker exec -it faaaar-db bash
  rs:
    cmds:
      - docker-compose exec server go mod download
      - docker-compose exec server go run main.go
  rf:
    cmds:
      - docker-compose exec front go mod download
      - docker-compose exec front go run main.go