version: '3'

tasks:
  build:
    cmds:
      - docker-compose up --build -d
  rbuild:
    cmds:
      - task stop
      - task build
  stop:
    cmds:
      - docker stop faaaar-front
      - docker stop faaaar-server
      - docker stop faaaar-db
  srv-e:
    cmds:
      - docker exec -it faaaar-server sh
  db-e:
    cmds:
      - docker exec -it faaaar-db bash
  run-srv:
    cmds:
      - docker-compose exec server go mod download
      - docker-compose exec server go run main.go
  run-frt:
    cmds:
      - docker-compose exec front go mod download
      - docker-compose exec front go run main.go